<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_btn-close</name>
   <tag></tag>
   <elementGuidId>1b99334b-8316-4ca9-8176-d0bdfff54afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>028c677b-a34b-45b7-b0da-39345fe6a03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close</value>
      <webElementGuid>76c0acf3-9a34-40ea-a02c-9ec92678d42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>a194c37a-4f78-4ff3-bd99-bd05aaad8530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>d56eb3c2-c7e9-4d50-b093-cac9cb19fc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;480&quot;]/span[@class=&quot;btn-close&quot;]</value>
      <webElementGuid>100b756f-9bad-4a80-aa58-3a1575ea6465</webElementGuid>
   </webElementProperties>
</WebElementEntity>
