<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_6</name>
   <tag></tag>
   <elementGuidId>f8230adb-0122-42c7-86b7-c311d490b70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[4]/nav/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1470719-51c5-43b1-ab6f-505f622ed7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>ecead8b3-3bc3-4989-afb3-469af96418ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://crazystylezs.com/product-categories/women?categories%5B0%5D=1&amp;categories%5B1%5D=15&amp;categories%5B2%5D=19&amp;sort-by=%22null%22&amp;num=0&amp;_=1708428678371&amp;page=6</value>
      <webElementGuid>d2cafbad-1532-4a2e-8398-401fa4309ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5b33760a-78b9-4ca9-83f4-3da6e64c5708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;pagination-area mt-20 mb-20 pagination-page&quot;]/nav[1]/ul[@class=&quot;pagination justify-content-start&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>43711a54-e7f0-439d-ba0d-d9052e7bfca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[4]/nav/ul/li[7]/a</value>
      <webElementGuid>5285b6e3-f49b-46bb-ab51-525dc1473d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'6')])[3]</value>
      <webElementGuid>5e3f0121-062b-40fb-b74a-b5ec0c6bad44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[12]/following::a[7]</value>
      <webElementGuid>5e4620c8-7829-4230-882d-87c1bb00cf02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.4,035.00'])[1]/following::a[8]</value>
      <webElementGuid>a21a58d1-7b9d-4ed7-a74f-ca5a37799cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/preceding::a[3]</value>
      <webElementGuid>9357667e-866b-4162-b22e-df89976517b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super Secure Payment'])[1]/preceding::a[3]</value>
      <webElementGuid>92780484-e88f-4b70-bccc-68020554bfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6']/parent::*</value>
      <webElementGuid>1c8c4dfd-e7ca-4cfa-9e6c-b9c27645de12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://crazystylezs.com/product-categories/women?categories%5B0%5D=1&amp;categories%5B1%5D=15&amp;categories%5B2%5D=19&amp;sort-by=%22null%22&amp;num=0&amp;_=1708428678371&amp;page=6')])[2]</value>
      <webElementGuid>a3534b0f-3d0e-40cc-8bee-50bf627a8a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/ul/li[7]/a</value>
      <webElementGuid>30be8769-8f0f-4fdc-9c74-9fc887b218de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://crazystylezs.com/product-categories/women?categories%5B0%5D=1&amp;categories%5B1%5D=15&amp;categories%5B2%5D=19&amp;sort-by=%22null%22&amp;num=0&amp;_=1708428678371&amp;page=6' and (text() = '6' or . = '6')]</value>
      <webElementGuid>b064005e-9134-452d-a339-ffa90e8f4e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
