<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews (11)</name>
   <tag></tag>
   <elementGuidId>466679e7-e86f-4894-b771-7d735a088a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reviews-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Reviews-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a533a5c-7fee-4f7d-b567-3d78a5a433cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reviews-tab</value>
      <webElementGuid>8a68d2ad-835b-4928-95e6-d0e7deccd0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9adc709b-f072-4c4d-8f64-d6523870a6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Reviews</value>
      <webElementGuid>04744ca0-d5ca-4b27-90f7-bd86f7cf4982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>083e526d-790d-4b71-afa2-b97c44e14efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reviews (11)</value>
      <webElementGuid>9cfba329-3080-4370-9080-857d905979f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reviews-tab&quot;)</value>
      <webElementGuid>dd033974-8ee3-4ae1-bf13-30ff098f78cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Reviews-tab']</value>
      <webElementGuid>74201b66-9518-4385-93db-3cb5017c278a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>16fdf164-a2cc-4e6f-ba1c-878b33c21f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reviews (11)')]</value>
      <webElementGuid>2ad78b02-4224-44b7-9a82-afd0b7ddf110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::a[1]</value>
      <webElementGuid>c3bc65d4-94bb-4247-ade2-2f907173f15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allen Solly'])[1]/following::a[2]</value>
      <webElementGuid>cb56a0fc-7140-4865-85eb-a014ab9ea000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DETAILS'])[1]/preceding::a[1]</value>
      <webElementGuid>c61330e8-d158-4f93-ba0f-2d5cfe0499de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teal Green solid sling bag'])[1]/preceding::a[1]</value>
      <webElementGuid>e0df420e-e972-44d4-a7a6-030d21ab91f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviews (11)']/parent::*</value>
      <webElementGuid>49267f9a-7627-4131-98c0-d2167a752687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#Reviews')])[2]</value>
      <webElementGuid>dc55ca89-a9b0-4ef3-8b2e-b1fa80746111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>75eedb09-85c5-4344-9be2-a9fea14a3a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'Reviews-tab' and @href = '#Reviews' and (text() = 'Reviews (11)' or . = 'Reviews (11)')]</value>
      <webElementGuid>a9aa6a15-0549-489c-a073-dc221c546fbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
