<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Images from customer (23)_img-responsive rounded border h-100</name>
   <tag></tag>
   <elementGuidId>4a3e091f-8fae-4d8c-bcc6-c139a7e7d48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Reviews']/div/div/div/a[5]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8d7d048-ff91-466b-9ff1-b07ec786c207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/reviews/pexels-richard-verbeek-572861-3-150x150.jpg</value>
      <webElementGuid>73b2ff38-64fc-4b20-9bfc-7c7c690c0b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Testing Product</value>
      <webElementGuid>6eb288e5-f5ca-4509-88e3-6b4b6e51c9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive rounded border h-100</value>
      <webElementGuid>289acf6d-1c2f-41d9-815f-964fc1d84ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reviews&quot;)/div[@class=&quot;my-3&quot;]/div[@class=&quot;block--review&quot;]/div[@class=&quot;block__images row m-0 block__images_total&quot;]/a[@class=&quot;col-lg-1 col-sm-2 col-3 more-review-images&quot;]/div[@class=&quot;position-relative&quot;]/img[@class=&quot;img-responsive rounded border h-100&quot;]</value>
      <webElementGuid>42cfb840-6dcb-4e89-b63a-1d19a27dadff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Reviews']/div/div/div/a[5]/div/img</value>
      <webElementGuid>4119d6b8-e73f-4275-9adf-001e043ae8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Testing Product'])[36]</value>
      <webElementGuid>528b8329-de35-443d-9852-8cde9d1f9b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div/img</value>
      <webElementGuid>2c948670-95bc-4c21-80bc-bf524ef0175c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://crazystylezs.com/storage/reviews/pexels-richard-verbeek-572861-3-150x150.jpg' and @alt = 'Testing Product']</value>
      <webElementGuid>564f4d34-880c-4f28-bba2-38914d9899d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
