<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Full Name</name>
   <tag></tag>
   <elementGuidId>eac5a8d9-49e3-487b-8abf-aa9d46204e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[text()='Full Name:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>10d276be-1703-4cb2-b0fb-57a91b63e207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>204c39be-06ef-49da-b612-789573a6912d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4fb2a84c-0da6-437a-a6d4-a80646701e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full Name:</value>
      <webElementGuid>9114d330-505e-417b-8e71-437238f812bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-12&quot;]/label[@class=&quot;required&quot;]</value>
      <webElementGuid>905430db-8551-4182-9a24-e9ba0eaf17ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/form/div/div/label</value>
      <webElementGuid>7b34ab1d-ac53-440d-894e-77227961018b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/label</value>
      <webElementGuid>83e00b8f-bff0-4757-9140-c692082cd3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Full Name:' or . = 'Full Name:')]</value>
      <webElementGuid>41e42d92-42c8-4ba8-b81e-d09ccb3a6084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
