<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select available addresses_addressemail</name>
   <tag></tag>
   <elementGuidId>1068c543-c3c1-46b0-b34a-4ea86bef6a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31fd9047-2341-4424-b34b-7927b741d8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ac2d5b5-b671-4121-a0c8-feb25fc82056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[email]</value>
      <webElementGuid>78202ca6-93b3-4a8c-bdbe-9bdb0cbd2b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_email</value>
      <webElementGuid>d4edb450-0435-477b-aa91-b6edbcc6ae70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>59373c94-978a-4694-8075-20a72f3e2561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>7704a395-02c0-4998-baf3-665a84db8aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_email&quot;)</value>
      <webElementGuid>2852ba2a-360a-46f3-9e51-2394fc947a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_email']</value>
      <webElementGuid>669e8a3c-6ae4-4993-86ed-8784cbe51363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>a791a2d2-0f4c-4083-b3d1-d6336d8b5d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>4afe19c3-44c1-4349-a12f-76e258bfc2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address[email]' and @id = 'address_email' and @placeholder = 'Email']</value>
      <webElementGuid>f95a4f95-8647-4daa-9eec-6b708e3d69de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
