<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select available addresses_addressaddress</name>
   <tag></tag>
   <elementGuidId>4b3b72db-8109-4e72-bc6d-81c832622ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2511863-cea6-4771-b6a3-f835aad82740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_address</value>
      <webElementGuid>769a02e0-4f0b-43b2-8ec2-78c425d87f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45d0442a-6694-4ed2-8cdb-11220becf2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>d529e7fa-dbd0-4d11-88a1-8cac0212e5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>73b3c4e5-beaf-4ac9-b10c-67698561b909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[address]</value>
      <webElementGuid>2146375f-b200-4fe1-aa5f-7b77465cd65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_address&quot;)</value>
      <webElementGuid>b83ea547-10fe-4567-9f71-70c4926c0c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_address']</value>
      <webElementGuid>8a3a950f-9d90-49f7-90f5-c9ca3a49d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[3]/div[4]/div/input</value>
      <webElementGuid>a7136e97-620a-4174-a06b-665c42ca519b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>093d4c62-dd06-4683-af1a-6876b09ff788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_address' and @type = 'text' and @placeholder = 'Address' and @name = 'address[address]']</value>
      <webElementGuid>f0a6c83d-662d-456a-a72d-73fdfae847c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
