<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select available addresses_addressphone</name>
   <tag></tag>
   <elementGuidId>01ecaf6b-c775-4d58-9cd4-8f57f431dee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>117d4f5e-fbb9-4095-a3e5-ce12a2cb13b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>9e6ebc67-2deb-4bd3-b922-67b07f3d6f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[phone]</value>
      <webElementGuid>bf7e8df2-bb2b-4853-ae4f-9f18e3f9891b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_phone</value>
      <webElementGuid>4d8a9f24-1212-4271-883f-9b8e52319d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>33748914-195e-4c6d-a0f0-4344bb4c19ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>bbeb5713-69ee-4f34-a9cf-59f03dadbab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumOnly(event)</value>
      <webElementGuid>20c1cf43-6ad6-4089-8ca8-374e8923200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ef641370-bc1a-423f-80d2-6d4fbcc688c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_phone&quot;)</value>
      <webElementGuid>d80cd1a2-0e05-4be3-8459-eb626b071dac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_phone']</value>
      <webElementGuid>d156df51-bd9e-4490-8d96-72d06bd1f3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>2013c2df-9847-40b4-9abf-d7236af2773c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>510cfe62-e76f-453b-83aa-cef7be9372a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'phone' and @name = 'address[phone]' and @id = 'address_phone' and @placeholder = 'Phone']</value>
      <webElementGuid>cb0345c8-1d80-4a1f-89bc-8be3295fbb6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
