<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select available addresses_addresszip_code</name>
   <tag></tag>
   <elementGuidId>26273d09-b97d-483d-b949-cadcc2e3b5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_zip_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_zip_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6272cc15-d6c1-4f3c-bdce-19eb4ecf2ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_zip_code</value>
      <webElementGuid>b26d6487-e964-4b51-8dff-50349c85830f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97f8d7ea-e4a1-490e-8ca1-816d778cb258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>0b01adf4-66fc-488a-bd3c-d3f45113ceac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip code</value>
      <webElementGuid>8e979ac1-7529-40cd-b5a6-02b47a9a8683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[zip_code]</value>
      <webElementGuid>669e3171-1ecb-481b-90e1-85710748240b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_zip_code&quot;)</value>
      <webElementGuid>09698f9c-60c2-427a-b5b4-944f558a99d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_zip_code']</value>
      <webElementGuid>ec0c47d8-7b2c-4e5a-90e4-5cb65a88f830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[3]/div[5]/div/input</value>
      <webElementGuid>810d2c3f-77b9-4919-a8f0-340cd0c4c59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>5c1b727d-8e74-4f28-b42b-7379ef5aca59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_zip_code' and @type = 'text' and @placeholder = 'Zip code' and @name = 'address[zip_code]']</value>
      <webElementGuid>7f71a96d-687c-4efe-a0ea-6f88bc0daf2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
