<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select available addresses_addressstate</name>
   <tag></tag>
   <elementGuidId>fb48c97e-bd7e-4378-9768-b3ed4eec6f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_state</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbdcee34-b4fa-4328-800f-6106bde98a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_state</value>
      <webElementGuid>d89095d3-dd78-4a97-ab6a-f9d26feddb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87acac7e-0ea2-4785-bae7-962b0628c15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>2465d20a-11e5-4940-a618-13fcb7a440b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>71533c42-9f82-46d6-9a7f-8601369b4318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[state]</value>
      <webElementGuid>95cd589b-6254-4e27-9df5-bdbb8e150f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_state&quot;)</value>
      <webElementGuid>62afe9dd-a81f-43cd-b9e5-f25c5045679a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_state']</value>
      <webElementGuid>96b0a3fd-1c70-40fd-828d-e3ee9ecc4f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>c1a29fd7-1e8d-4b6f-af1a-53fcf27db7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>6865e54c-51cc-475e-92e8-175d98f0b74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_state' and @type = 'text' and @placeholder = 'State' and @name = 'address[state]']</value>
      <webElementGuid>2f3032f2-9b49-4270-81e0-986491285d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
