<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Embroidered Semi-Stitched Lehenga Choli W_a6a127</name>
   <tag></tag>
   <elementGuidId>10c3da01-39e2-47c2-8441-bc7aea88fc59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.zoom-icon > i.fi-rs-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div/div/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aff29f02-9a2a-4de2-9bcb-87eb3730b20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rs-search</value>
      <webElementGuid>cf1d52da-0438-483c-ba36-a00bc6963cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9&quot;]/div[@class=&quot;product-detail accordion-detail&quot;]/div[@class=&quot;row mb-50 mt-30&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-xs-12 mb-md-0 mb-sm-5&quot;]/div[@class=&quot;detail-gallery&quot;]/span[@class=&quot;zoom-icon&quot;]/i[@class=&quot;fi-rs-search&quot;]</value>
      <webElementGuid>abba0254-eb1a-4556-a36c-4f07c37ebde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div/div/div/span/i</value>
      <webElementGuid>f6e700ea-8026-48cb-8f21-3cede73adb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/i</value>
      <webElementGuid>5a3d5184-8878-4e97-8a6d-d523eb7a3e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
