<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Company</name>
   <tag></tag>
   <elementGuidId>bb35bce3-8633-4da1-b36b-3ba7502ad320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.widget-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>cd7f921c-e296-4439-890e-6e12bd50c53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-title</value>
      <webElementGuid>6b725839-d038-4a63-8093-6c3f31ef3f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>3f539b0b-2b70-4d62-b2d5-ebdba0b4ac73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[@class=&quot;main&quot;]/section[@class=&quot;section-padding footer-mid&quot;]/div[@class=&quot;container pt-15 pb-20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;footer-link-widget col wow animate__ animate__fadeInUp animated&quot;]/h4[@class=&quot;widget-title&quot;]</value>
      <webElementGuid>5cca14e8-4d59-4680-aa0c-17e1eceaa557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4</value>
      <webElementGuid>b69e6391-73e6-42a2-a461-197d7f89c716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Company' or . = 'Company')]</value>
      <webElementGuid>671e20de-459b-4dff-88f7-7c1614ee7c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
