<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Digital Floral Flared Semi- Stitched Leh_b97d54</name>
   <tag></tag>
   <elementGuidId>b6d0d917-badf-4724-acb4-7e77f6e96644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.title-detail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div/div[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b3ae653d-ee92-4a37-8907-3848041f72ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-detail</value>
      <webElementGuid>ed69ca9a-95cc-4060-866f-7298e2e53262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Digital Floral Flared Semi- Stitched Lehenga With Dupatta</value>
      <webElementGuid>68bd6afe-f78f-43ac-864f-8248273503c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9&quot;]/div[@class=&quot;product-detail accordion-detail&quot;]/div[@class=&quot;row mb-50 mt-30&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;detail-info pr-30 pl-30&quot;]/h2[@class=&quot;title-detail&quot;]</value>
      <webElementGuid>1b07fbd8-7e32-42e3-bf29-c99494579fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div/div[2]/div/h2</value>
      <webElementGuid>90ffcad2-04e9-4d9f-ae11-7ab39b5f3035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hot'])[1]/following::h2[1]</value>
      <webElementGuid>8b884b80-34bd-4559-ab06-3857e4c1cdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Floral Flared Semi- Stitched Lehenga With Dupatta'])[2]/following::h2[1]</value>
      <webElementGuid>a73f9d48-bae4-42a6-8923-ddaafea20f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0 reviews)'])[1]/preceding::h2[1]</value>
      <webElementGuid>cb474257-e0cb-47f8-ab00-6f00d618b0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.3,999.00'])[1]/preceding::h2[1]</value>
      <webElementGuid>4db346d3-8bb7-4548-9568-b983955a4f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>e77fab44-7ec0-4d99-85ef-4498b35ce30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Digital Floral Flared Semi- Stitched Lehenga With Dupatta' or . = 'Digital Floral Flared Semi- Stitched Lehenga With Dupatta')]</value>
      <webElementGuid>d7581bf5-2093-470f-b360-11611e4e5821</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
