<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscribe_1</name>
   <tag></tag>
   <elementGuidId>f98c911f-0739-438e-a37d-caaf14757bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide02']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slick-slide02</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb5e5e7e-2e6a-4b60-924a-1babcacc369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/3.jpg</value>
      <webElementGuid>478ca7bb-9cba-4eba-8728-e8b416c76c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablet-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/3.jpg</value>
      <webElementGuid>646f8519-406d-4cdb-9ff6-c32717bdaf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/3.jpg</value>
      <webElementGuid>462188d8-ea1b-4232-ad97-ecaff895e55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-hero-slider single-animation-wrap slick-slide</value>
      <webElementGuid>5a847526-f47d-4731-846a-f223d11041e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slick-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8487d094-a9e6-4272-9a34-d01f1fe9fb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36bea85a-4744-4d0f-86fa-c7361dcc6e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9616cdd-db56-4993-b79e-ab20db2c6790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>126b2290-a714-4b17-8819-9ab00952abca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slick-slide02</value>
      <webElementGuid>ec774968-80c7-4bda-961d-00aa3c70b0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>slick-slide-control02</value>
      <webElementGuid>e2603d62-3027-4847-8e5a-7e1278ec799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Subscribe</value>
      <webElementGuid>c0bd60db-993b-4f66-be8b-436023cd5e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide02&quot;)</value>
      <webElementGuid>08386f9e-2f92-4522-87d2-5adaa9903677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slick-slide02']</value>
      <webElementGuid>0561eafa-5696-41e1-a3c6-7d3c1653a487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>fe1c3a26-ba09-44f1-aa4e-b39100801d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>360ba126-0bdb-4107-9604-f2c61f744cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slick-slide02' and (text() = '  Subscribe' or . = '  Subscribe')]</value>
      <webElementGuid>d53ca455-557c-483e-9bbc-3fa14db0942b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
