<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscribe</name>
   <tag></tag>
   <elementGuidId>61437222-4a6a-4977-9014-25345ead7a7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide03']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slick-slide03</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>946b9a70-a153-4b2f-9036-7559e6d4830d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/4.jpg</value>
      <webElementGuid>376b4454-7f65-408c-a885-3ca60d149d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablet-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/4.jpg</value>
      <webElementGuid>75083773-a8a0-4466-b72c-cda976dca977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/4.jpg</value>
      <webElementGuid>795bdca7-d4ee-4e78-aeb4-3bb5579b08b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-hero-slider single-animation-wrap slick-slide slick-current slick-active</value>
      <webElementGuid>8985f950-1871-42ae-bdf5-229ef1c5771f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slick-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b96ec900-1fd0-4b5c-aa44-522b8d07d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97b88a12-7e8e-4c78-b996-3a6d1c2da171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d8050057-1ec8-4576-a33e-aba36ed3b9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>7a6cec3a-4714-4dd6-8b5b-1a65255f6eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slick-slide03</value>
      <webElementGuid>5bde0fc9-dce5-4e57-9fb5-9ff37ef02d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>slick-slide-control03</value>
      <webElementGuid>5e1bc6b1-7316-4601-9fae-7c7aa8f723ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Subscribe</value>
      <webElementGuid>545ca16f-3f86-442c-94fa-aae292383295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide03&quot;)</value>
      <webElementGuid>42adefa2-b0d6-4198-b5e0-49b95e8a3e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slick-slide03']</value>
      <webElementGuid>0d17ee1e-c7d5-4fd6-8b32-e21ed52d43d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section/div/div/div/div/div/div/div/div[4]</value>
      <webElementGuid>9cefb97d-5452-4c2c-b8cf-e10b7309c03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[4]</value>
      <webElementGuid>1bc939e4-668b-4d28-89d8-b75aeac5b02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slick-slide03' and (text() = '  Subscribe' or . = '  Subscribe')]</value>
      <webElementGuid>e6567a78-77d1-4798-af5c-179a0c6a880a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
