<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscribe_1_2</name>
   <tag></tag>
   <elementGuidId>02086b94-4174-4c19-8a21-ed9226dd4908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slick-slide00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ac44f34-5d0e-4158-b453-b4848622c342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/1.jpg</value>
      <webElementGuid>90c668e6-268e-48c4-b43a-07e601ee0b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablet-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/1.jpg</value>
      <webElementGuid>ed4f8545-b372-4de9-adfc-4cd7c5a3f89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/1.jpg</value>
      <webElementGuid>ab3c55fc-bc1d-421a-9c06-099b2beebc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-hero-slider single-animation-wrap slick-slide</value>
      <webElementGuid>f7c977d9-f4a8-4784-99a7-6ddb804e1cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slick-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0306577-5bfc-407d-8136-fa3ae5aa05ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f2bcb98-f84e-4234-aa15-f829fe559dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71e4af76-93ab-4502-b141-fda2b3ea2e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>58f0ce11-4bcd-40c0-9ce5-f2b570ddc894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slick-slide00</value>
      <webElementGuid>3a3ba74a-a2fb-4e67-8683-3469ab35f118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>slick-slide-control00</value>
      <webElementGuid>19991b78-a148-420c-9daa-6f0f194c105b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Subscribe</value>
      <webElementGuid>bb48428d-e892-4cf1-ab62-0b8a11ccaef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide00&quot;)</value>
      <webElementGuid>923fccc4-6175-4d72-9965-fcfa6d99bd2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slick-slide00']</value>
      <webElementGuid>b6d92f14-bf13-4435-9b54-fa9281799144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section/div/div/div/div/div/div/div/div</value>
      <webElementGuid>7f4879aa-5b89-4e2a-8ae6-901bb7a63f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/div/div</value>
      <webElementGuid>fe7d894a-ec01-41ee-8fe0-c405b7e65e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slick-slide00' and (text() = '  Subscribe' or . = '  Subscribe')]</value>
      <webElementGuid>3dd37740-063c-41fb-8a1d-c449b2c8a7e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
