<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Traditional Wear</name>
   <tag></tag>
   <elementGuidId>882a3d20-acc1-449f-b413-63c62cb941aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div/section[4]/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.section-title.mb-35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>e0b59bac-89c0-46a2-b616-b5ed19cefe81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title mb-35</value>
      <webElementGuid>8a375761-4310-4e59-bed5-0e7f31d7c731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Traditional Wear</value>
      <webElementGuid>f17037f5-9cb8-44a9-bfa2-7dff21377700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;ck-content&quot;]/section[@class=&quot;bg-grey-9 section-padding-60&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;heading-tab d-flex&quot;]/div[@class=&quot;heading-tab-left wow fadeIn animated animated&quot;]/h3[@class=&quot;section-title mb-35&quot;]</value>
      <webElementGuid>e8384073-c1b1-4843-8320-763df003749b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section[4]/div/div/div/h3</value>
      <webElementGuid>be5bd74e-34e4-40b7-8076-9272f454681b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>bb628a4f-9c7b-4ab0-b5ab-e05af98b82a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Traditional Wear' or . = 'Traditional Wear')]</value>
      <webElementGuid>c47edd16-c630-468c-8e32-8169557f1508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
