<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_hover-img</name>
   <tag></tag>
   <elementGuidId>2a185cbf-8744-425d-be7f-b4e1175d3da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.hover-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div/section[5]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bec0fe2c-2334-40f9-bdc4-d8a790f406d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-img</value>
      <webElementGuid>0f2daef7-a426-4d8b-a2e6-a83bef58c571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://classicculture.in/storage/products/artboard-2-440-400x400.jpg</value>
      <webElementGuid>a8f70b33-dcb2-4649-862d-c7c56f231374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Women Grey Lace Empire Top</value>
      <webElementGuid>4c23053d-83f2-431b-a6c3-225b559adca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;ck-content&quot;]/section[@class=&quot;bg-grey-9 section-padding-60&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab-content wow fadeIn animated animated&quot;]/div[@class=&quot;tab-pane fade show active&quot;]/div[@class=&quot;row product-grid-4&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-img-action-wrap&quot;]/div[@class=&quot;product-img product-img-zoom&quot;]/a[1]/img[@class=&quot;hover-img&quot;]</value>
      <webElementGuid>9c38429f-7880-435c-8121-4c92a8a3aa0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section[5]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      <webElementGuid>8a5feae7-77ae-4dd3-975f-aa9539a33fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Women Grey Lace Empire Top'])[2]</value>
      <webElementGuid>fe29a944-6d95-4ffc-85e5-30354aa377b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>91a0d4e2-4489-4bb6-9b0a-57cae08fd6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://classicculture.in/storage/products/artboard-2-440-400x400.jpg' and @alt = 'Women Grey Lace Empire Top']</value>
      <webElementGuid>2be23ac5-7559-4a28-bda3-24faed92ed11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
