<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Rs.400.00_fi-rs-trash</name>
   <tag></tag>
   <elementGuidId>6a2fcde5-8f12-4618-a59f-e30ccfe2c30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr/td[6]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fi-rs-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4450b21c-0f45-47ba-a610-ceefe9de887a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rs-trash</value>
      <webElementGuid>21aff89d-89a8-47c9-9925-4df09c7003ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-80 mt-50 section--shopping-cart&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;table-responsive shopping-summery&quot;]/table[@class=&quot;table table-wishlist table--cart&quot;]/tbody[1]/tr[@class=&quot;pt-30&quot;]/td[@class=&quot;action text-center&quot;]/a[@class=&quot;text-body remove-cart-button&quot;]/i[@class=&quot;fi-rs-trash&quot;]</value>
      <webElementGuid>2b47d81a-3cc1-4f74-9764-a1cce1a477e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr/td[6]/a/i</value>
      <webElementGuid>d5e629c9-b8e0-44ea-af3c-7ff308aeb8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>500bff84-6b6c-4193-a9fb-dba080500e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
