<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>22ed5dbf-ed2c-4399-a23e-dbc732245d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-small.d-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf00ed22-d951-44de-a81c-cd9fc39edb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://classicculture.in/customer/orders/view/800</value>
      <webElementGuid>dd141c75-d55a-4fec-a84a-dbd6a88d5637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-small d-block</value>
      <webElementGuid>4e64d26b-c434-422b-bc58-48d1fe47b07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>73f62123-adf8-4ae3-97b9-b5f42b927b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[5]/a[@class=&quot;btn-small d-block&quot;]</value>
      <webElementGuid>9f6e29de-06e8-44be-b094-d7944be0b3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr/td[5]/a</value>
      <webElementGuid>21e15801-f985-420c-ad0c-4823a9835cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[3]</value>
      <webElementGuid>475ab2b9-6d07-4159-9a02-eb9562e5d5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::a[1]</value>
      <webElementGuid>91096f5f-81c4-4c5d-b239-1161cae71b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.354.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>73ded167-c734-4cac-8083-dd2ee6e83a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000799'])[1]/preceding::a[1]</value>
      <webElementGuid>d9009812-ef2b-4676-98b6-47cce4bfffce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.354.00 for 1 item(s)'])[2]/preceding::a[1]</value>
      <webElementGuid>2733a61a-b0f3-4bb5-9053-6d374507c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>9b9e64ec-85fa-4240-a867-ce718b663a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/800')]</value>
      <webElementGuid>7b136f06-8591-4d18-8d90-8fec493ac5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>cfda3c01-8563-40f6-986f-f824e7d3ba59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/800' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>376cac3e-bce7-4b35-b648-8bee92024e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[2]</value>
      <webElementGuid>cb78abcb-3f5f-45ce-9541-0b2af2d2eb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000788'])[1]/preceding::a[1]</value>
      <webElementGuid>39c6e50c-6d34-4370-bab3-c63400bbc492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/789')]</value>
      <webElementGuid>f40bdd75-44a8-48b7-9181-d36a1c919b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/789' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>38e8d056-9995-490f-8706-1d148cee978c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr[5]/td[5]/a</value>
      <webElementGuid>ef1c25ca-c2b8-49c0-93cd-888d47f2bb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[8]</value>
      <webElementGuid>de33c4cd-8c71-4aa9-b840-98c1ed0d939b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.994.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>a3c57c64-6a62-45e0-bfd8-357f9bd81a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000506'])[1]/preceding::a[1]</value>
      <webElementGuid>5574f951-01e6-43a2-a3c9-9894817517e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.994.00 for 1 item(s)'])[2]/preceding::a[1]</value>
      <webElementGuid>e8f4ab2b-d26f-432f-9f22-09ef7d8188a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/507')]</value>
      <webElementGuid>48a3d83b-c1bd-4ab1-9626-8a6a9bbd6168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/a</value>
      <webElementGuid>11ed21cf-cfcd-40d3-a8f0-cd6d4b749e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/507' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>0aa4cbdd-fa91-4650-adb9-7d4aa8990490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>2c574169-2b7c-4456-8389-43635f0fea58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::a[1]</value>
      <webElementGuid>4bfa4bca-c9db-4018-b4b9-f83b540459e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.672.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>d09381bf-50f7-4c61-8729-370dd36c25ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000656'])[1]/preceding::a[1]</value>
      <webElementGuid>1db56761-698e-4fbe-8e96-438d4325af64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.725.00 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>ae12c409-1453-4fa6-9b87-c007288ec074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/704')]</value>
      <webElementGuid>b25b8464-840a-46e7-9ef2-5326c40ed8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/704' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>88d3204a-73ae-4c00-aad2-f607e9e40c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[4]</value>
      <webElementGuid>de9c0cb9-b6ba-404f-ba4d-f1ee86452d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>74c8f115-2d25-476b-8ca9-9f01d240498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[2]/following::a[1]</value>
      <webElementGuid>8c1a86e9-59dc-4036-846d-7c1b14cfb03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.725.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>cf6c1d2c-e399-43cf-9b42-a836d9cfe5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000636'])[1]/preceding::a[1]</value>
      <webElementGuid>b990226d-a591-4d9b-9f37-2676213e4030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.5,227.52 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>a6f3d600-8077-45ba-ac76-d9bd5e0272ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/656')]</value>
      <webElementGuid>f82f8db8-802a-4957-bc77-317fd6f0a436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/a</value>
      <webElementGuid>b9af59e9-0d1d-47dc-b68a-b4b56af80998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/656' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>714bf712-60cb-450a-bcd9-c4cfbf961def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr[8]/td[5]/a</value>
      <webElementGuid>e136e999-552d-4b80-9455-ef94713260c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[11]</value>
      <webElementGuid>229bf4d3-d948-4397-b598-d229e60ac350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[6]/following::a[1]</value>
      <webElementGuid>f144c6e0-3b66-4366-b126-670e8ec14b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.20.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>4440c542-a2e1-4e42-98af-65fecafdb0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000538'])[1]/preceding::a[1]</value>
      <webElementGuid>2138d930-d8c5-40cd-8969-8a1c554073a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.5,866.78 for 5 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>372c2eeb-9057-4f80-a31c-09c1ca32224a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/545')]</value>
      <webElementGuid>1dc85e17-d8c3-4547-9209-177a6a493e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[5]/a</value>
      <webElementGuid>49039c85-7940-4cf0-b7a5-e5d42b5a10ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/545' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>fddb2b1b-df77-4449-8078-1e6c6f8c0d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr[3]/td[5]/a</value>
      <webElementGuid>701d9588-28aa-45f2-b5e1-a0424d2b200d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[6]</value>
      <webElementGuid>a78490f2-b810-40d9-871e-091426847d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.5,227.52 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>2bfa2673-4af5-4682-a2ec-a534f5dbecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000568'])[1]/preceding::a[1]</value>
      <webElementGuid>e5ef07e1-81dc-4416-b8e6-e133e98e0b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.2,558.76 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>a69182ad-ef7f-4789-a179-27ef508da097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/636')]</value>
      <webElementGuid>002cdeaf-ceb0-4050-975f-f5445ae58cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/a</value>
      <webElementGuid>70b5075b-1704-424c-b408-45c6d58ce837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/636' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>14745e5c-3f65-4d10-86af-029b3e345740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
