<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View_1</name>
   <tag></tag>
   <elementGuidId>f07bc3a3-c661-4362-94de-1d47d50c7fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(5) > a.btn-small.d-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[text()='View' and contains(@href,'view')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf468cac-5097-4943-9830-0128206ed596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://classicculture.in/customer/orders/view/499</value>
      <webElementGuid>4dd50156-b477-444c-b9bf-321d08ece248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-small d-block</value>
      <webElementGuid>b983f377-d0b3-45bb-8f6e-f3cd8fe02186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>8fffc7eb-98e8-4a42-8fab-2c2ea0c0ad0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[5]/a[@class=&quot;btn-small d-block&quot;]</value>
      <webElementGuid>a2d6d5b0-17ee-410e-ac5f-8eae46292ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>2ea387ff-3953-4388-9b96-231e937e357a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>7e0cdf5f-f751-44f8-97fb-7a0d435ea3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::a[1]</value>
      <webElementGuid>f888c77e-3d49-4829-80ed-ce9189c42108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.1,053.00 for 1 item(s)'])[2]/following::a[1]</value>
      <webElementGuid>5f49065f-d44d-4c09-8475-4a7287118284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000498'])[1]/preceding::a[1]</value>
      <webElementGuid>9f3090de-a857-4bbf-8d06-a218b58779c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.994.00 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>076fe8c0-c05a-4b7f-af92-ff4b2fc1347a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/499')]</value>
      <webElementGuid>69672630-7a14-45d2-b656-79d10af1d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/a</value>
      <webElementGuid>2c80fea4-b5d1-4b1c-9465-1de586f08c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/499' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>80044f26-6b83-4966-8b6c-4e5925b8fa33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr[5]/td[5]/a</value>
      <webElementGuid>6519465a-ef88-4518-8c32-f613b673fc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[8]</value>
      <webElementGuid>71c8bb56-5139-4766-9133-c618b509df87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.472.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>d48fef19-e505-4c83-b36d-a40e64f441c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000548'])[1]/preceding::a[1]</value>
      <webElementGuid>ff1bf6ab-2405-4175-bb5f-58ecd6427e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.5,127.52 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>7389aee8-4712-43f3-a9c5-1da6da20c4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/566')]</value>
      <webElementGuid>648a58b2-014c-4700-b564-dc3b13066509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/a</value>
      <webElementGuid>d857cb39-50a9-4fbf-be2b-f6e82b0c2fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/566' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>8b317e68-0e89-4981-a25b-9add00c0e640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/table/tbody/tr/td[5]/a</value>
      <webElementGuid>605c89a3-db9f-47ea-b785-11251d15e7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[4]</value>
      <webElementGuid>b7a1f18e-6a2a-4524-9055-c110cd5fb6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::a[1]</value>
      <webElementGuid>78856e63-03f9-4569-afbd-9c266be6cf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.672.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>6188b239-ff2f-4c69-8d68-06eb245a7c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000656'])[1]/preceding::a[1]</value>
      <webElementGuid>55a0321b-fd8a-46e7-86b6-794122aa0e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.725.00 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>e6079a58-cd89-46ee-8c19-d1603718ee73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>1040fa09-1375-4157-8165-dc1814a34c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/704')]</value>
      <webElementGuid>5c2d8cd0-f5bc-4770-a003-51d64da655bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>13e9e9cc-aa44-464f-bbf7-9c31785bd686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/704' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>3c89c9c7-7911-4343-a6a3-d7a171d875b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[2]/following::a[1]</value>
      <webElementGuid>4398184a-ede2-4878-bd63-356baeda62e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.725.00 for 1 item(s)'])[1]/following::a[1]</value>
      <webElementGuid>6cd718b0-1992-44c4-a6b5-d9fe23e7b09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10000636'])[1]/preceding::a[1]</value>
      <webElementGuid>82b4d6fc-97a9-4b44-a5fb-2f6666fa3e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.5,227.52 for 1 item(s)'])[1]/preceding::a[1]</value>
      <webElementGuid>8cf35b7b-301d-4f05-981d-ae514c1b05b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/customer/orders/view/656')]</value>
      <webElementGuid>cc066a67-ef4f-4a6a-b7dd-111a8e792f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/customer/orders/view/656' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>40fae4e5-d85c-4b64-a36a-bf6aab157ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
