<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_View_fi-rs-arrow-small-left</name>
   <tag></tag>
   <elementGuidId>83df96aa-b00a-46ea-b9bc-9479fd74b755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fi-rs-arrow-small-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='scrollUp']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f58aeffa-98fc-4e9b-98cf-37f96df8314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rs-arrow-small-up</value>
      <webElementGuid>055f2d66-9bc4-498a-ae6d-d62126fa03f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollUp&quot;)/i[@class=&quot;fi-rs-arrow-small-up&quot;]</value>
      <webElementGuid>41f86366-28f5-4723-9064-a6519ae590ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='scrollUp']/i</value>
      <webElementGuid>07b18ad8-4953-46d0-83aa-8aefa2b4f992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/a/i</value>
      <webElementGuid>5c07f855-d9d5-4a01-b444-e9c05cc4ed1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/div/div/nav/ul/li/a/i</value>
      <webElementGuid>03b9cdc1-4757-4b09-8d25-880f6125fb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/nav/ul/li/a/i</value>
      <webElementGuid>4efe39bf-3467-480a-b362-4fe590386199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
