<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Send Password Reset Link</name>
   <tag></tag>
   <elementGuidId>31c1aa56-209a-4a73-a627-8f2a6d5e2ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.form--auth.form--login > div.form-group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/section/div/div/div/div/div/form/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e9fa1bf-ba4a-49e7-8c25-89ac7b8b1acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group</value>
      <webElementGuid>443797e6-5bd1-46d2-a068-fed4051a9359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send Password Reset Link</value>
      <webElementGuid>43fd0b22-7f1b-4198-9862-c58d8e966dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/section[@class=&quot;pt-100 pb-100&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 m-auto&quot;]/div[@class=&quot;login_wrap widget-taber-content p-30 background-white border-radius-10&quot;]/div[@class=&quot;padding_eight_all bg-white&quot;]/form[@class=&quot;form--auth form--login&quot;]/div[@class=&quot;form-group&quot;]</value>
      <webElementGuid>b3a9c815-2ebe-4bd0-b77a-a62685184983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/section/div/div/div/div/div/form/div[2]</value>
      <webElementGuid>29ba0c6f-9726-4aaf-9420-ecc1db8af4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::div[1]</value>
      <webElementGuid>dce7ee8e-1d01-4ef4-b588-c6cfa8c00255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::div[3]</value>
      <webElementGuid>d6cf924a-1097-462b-8a53-5878d4cd87c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/preceding::div[1]</value>
      <webElementGuid>d66802fb-62fa-4e95-b64a-eebf330c13ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/form/div[2]</value>
      <webElementGuid>24235d6c-3fb3-4fc8-b249-a8fe7b1ac80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Send Password Reset Link' or . = 'Send Password Reset Link')]</value>
      <webElementGuid>5454441a-d3bc-4539-b0f7-9a1be84d5e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
