<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed To Checkout</name>
   <tag></tag>
   <elementGuidId>01d50bc4-b13a-4836-8693-a75482138090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Proceed To Checkout ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;checkout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af2754fb-cb7b-47c5-8c7d-efe9f736af3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>23799d86-da4c-4af6-a321-4d9d6c80ec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>d445c579-e686-43ce-9e4a-4a417658390e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mb-20 w-100</value>
      <webElementGuid>d737f1a6-ca84-4a4e-9fe6-381a64ffb383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed To Checkout </value>
      <webElementGuid>adaab9a6-60d5-402f-8d35-7f4ca2516d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-80 mt-50 section--shopping-cart&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;border p-md-4 cart-totals ml-30&quot;]/button[@class=&quot;btn mb-20 w-100&quot;]</value>
      <webElementGuid>f21da509-f5e6-4cee-b097-cd454662f592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='checkout']</value>
      <webElementGuid>8cc690dd-4f8d-4077-b448-f96c4b7c40be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/form/div/div[2]/div/button</value>
      <webElementGuid>7d5e5eac-b7b6-4448-9dc5-5c835478fdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.3,184.82'])[3]/following::button[1]</value>
      <webElementGuid>f3ce88e4-9472-4e2a-9acd-c600fc58afd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Shipping fees not included)'])[1]/following::button[1]</value>
      <webElementGuid>1d6029fe-a29f-4337-a476-085d1d4babd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/preceding::button[1]</value>
      <webElementGuid>008430d3-e0b5-4377-bc66-32a81e74101f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super Secure Payment'])[1]/preceding::button[2]</value>
      <webElementGuid>cdaac901-4a0f-4f4b-bcb7-1ee051de16a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed To Checkout']/parent::*</value>
      <webElementGuid>1e247d6c-39a9-4dbd-8065-b9848bf328d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>6c3c6a95-3d03-498a-9782-59626476b4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'checkout' and (text() = 'Proceed To Checkout ' or . = 'Proceed To Checkout ')]</value>
      <webElementGuid>c9d521fc-c0f8-4ff7-92f9-1087184525fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
