<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>viewcart2</name>
   <tag></tag>
   <elementGuidId>76ac0c3e-bc71-418f-b08e-37cb14e8182c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>&#xd;
//div[@class=&quot;header-right&quot;]//a[contains(text(),'View')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
