<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sarees_hover-img</name>
   <tag></tag>
   <elementGuidId>07d77d82-e6c5-4790-9411-e74c366b7655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div/section[4]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.hover-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b68fd968-f857-4cab-b8c4-752deb22b076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-img</value>
      <webElementGuid>e82c958e-0769-40f7-80c0-e7edd08a6514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/products/2-110-400x400.jpg</value>
      <webElementGuid>372bce1d-21d9-4311-82d0-131dfacc2567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Women Yellow Bandhani Printed Maxi Dress</value>
      <webElementGuid>f6a6668e-b818-4f45-aeee-934aa257bc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;ck-content&quot;]/section[@class=&quot;bg-grey-9 section-padding-60&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab-content wow fadeIn animated animated&quot;]/div[@class=&quot;tab-pane fade show active&quot;]/div[@class=&quot;row product-grid-4&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-img-action-wrap&quot;]/div[@class=&quot;product-img product-img-zoom&quot;]/a[1]/img[@class=&quot;hover-img&quot;]</value>
      <webElementGuid>6f59de2f-8ff4-44a1-abc5-8e6c18927c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section[4]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      <webElementGuid>08d57891-2153-44e8-a3c5-ce47a903f1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Women Yellow Bandhani Printed Maxi Dress'])[2]</value>
      <webElementGuid>a433ba91-b579-4b84-8513-8a7f754f233c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>77537b9d-3bc5-4509-8036-d6cf2d229c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://crazystylezs.com/storage/products/2-110-400x400.jpg' and @alt = 'Women Yellow Bandhani Printed Maxi Dress']</value>
      <webElementGuid>250df51a-2d85-4a49-b29d-4dd15c95a5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Women Yellow Bandhani Printed Maxi Dress'])[4]</value>
      <webElementGuid>921bee5b-4f4f-4408-a195-d9c1c0e49bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
