<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>11fd82a9-ddac-452d-9ccc-f2b0ac107896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>figure.border-radius-10.slick-slide.slick-current.slick-active > a > img[alt=&quot;Testing Product&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div/div/div/div/div/div/figure[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a728ddb5-a3df-41cf-9ca1-34563c037568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/dropbox-8254221001031053-800x800.webp</value>
      <webElementGuid>6523e918-373b-448d-84a1-265040c36d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Testing Product</value>
      <webElementGuid>41891c60-db16-4c50-a079-73c8f497dc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9&quot;]/div[@class=&quot;product-detail accordion-detail&quot;]/div[@class=&quot;row mb-50 mt-30&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-xs-12 mb-md-0 mb-sm-5&quot;]/div[@class=&quot;detail-gallery&quot;]/div[@class=&quot;product-image-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/figure[@class=&quot;border-radius-10 slick-slide slick-current slick-active&quot;]/a[1]/img[1]</value>
      <webElementGuid>30f2eb9f-d1bd-4f39-8265-0027debeddc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div/div/div/div/div/div/figure[2]/a/img</value>
      <webElementGuid>d0677e4a-0032-45d1-9646-0ddfcd3ddfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Testing Product'])[2]</value>
      <webElementGuid>afcd7006-079c-4754-80ec-44d67837fa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure[2]/a/img</value>
      <webElementGuid>f2c89ca3-d3f6-4f10-8689-eca21edb0e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://crazystylezs.com/storage/dropbox-8254221001031053-800x800.webp' and @alt = 'Testing Product']</value>
      <webElementGuid>9b70458c-5b90-4890-98ce-5f4d7eec9ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
