<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sarees_hover-img</name>
   <tag></tag>
   <elementGuidId>de4e245a-9f14-4f36-b069-8e4623a80857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div/section[4]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.hover-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fbbedd0c-4746-4d61-bb02-bc7a56be220b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-img</value>
      <webElementGuid>41fc6c1c-732f-4544-b30b-c395212032f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/products/2-110-400x400.jpg</value>
      <webElementGuid>990c73f4-cb02-4038-ab72-8879c3b76627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Women Yellow Bandhani Printed Maxi Dress</value>
      <webElementGuid>82eb0289-bc89-4340-bcf1-b947d0c973d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;ck-content&quot;]/section[@class=&quot;bg-grey-9 section-padding-60&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab-content wow fadeIn animated animated&quot;]/div[@class=&quot;tab-pane fade show active&quot;]/div[@class=&quot;row product-grid-4&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-img-action-wrap&quot;]/div[@class=&quot;product-img product-img-zoom&quot;]/a[1]/img[@class=&quot;hover-img&quot;]</value>
      <webElementGuid>76d39c3a-fd4b-4e5b-856e-b664d08c4132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section[4]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      <webElementGuid>c7ccbc0a-feec-4f01-ac7c-d09ffcf29d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Women Yellow Bandhani Printed Maxi Dress'])[2]</value>
      <webElementGuid>6b4f636b-87bc-4bc6-8cef-1f84447f8e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>38965621-7e20-4c9f-971b-13f8ffe507b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://crazystylezs.com/storage/products/2-110-400x400.jpg' and @alt = 'Women Yellow Bandhani Printed Maxi Dress']</value>
      <webElementGuid>10810956-3ef5-42ec-b6fa-ce33fc394941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
