<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fi-rs-trash</name>
   <tag></tag>
   <elementGuidId>209c8af1-f4d3-467b-9654-302022880c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr[2]/td[6]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1d6bcfa7-d44b-4ad4-bea4-983a9aa4cece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rs-trash</value>
      <webElementGuid>f0cece92-83ef-43f3-b693-da7e41228500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-80 mt-50 section--shopping-cart&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;table-responsive shopping-summery&quot;]/table[@class=&quot;table table-wishlist table--cart&quot;]/tbody[1]/tr[@class=&quot;pt-30&quot;]/td[@class=&quot;action text-center&quot;]/a[@class=&quot;text-body remove-cart-button&quot;]/i[@class=&quot;fi-rs-trash&quot;]</value>
      <webElementGuid>35bf8796-25ed-4a37-bb20-bf7908407499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr[2]/td[6]/a/i</value>
      <webElementGuid>88399436-8edd-4794-8a1c-799ba056af29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/a/i</value>
      <webElementGuid>3d1d828d-6e56-4cf7-b393-2559f0b9e210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr/td[6]/a/i</value>
      <webElementGuid>3c58873d-98cb-4ff9-97dc-96415b036c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>c27413a9-bf3f-4591-9687-0cbe15cfbce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
