<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email is requiredContent is required</name>
   <tag></tag>
   <elementGuidId>615777a2-0075-42d8-9a1d-4b5e9099312c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.contact-message.contact-error-message.mt-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/section/div/section/div/div/div/div/form/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b63eeb4-f7b7-46e0-9b43-f7d64df16c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact-message contact-error-message mt-30</value>
      <webElementGuid>0e6e9dbe-91eb-4f3f-b909-549ed623b1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email is requiredContent is required</value>
      <webElementGuid>d68d3641-a247-4762-958a-d0d4dc472a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;mt-60 mb-60&quot;]/div[@class=&quot;ck-content&quot;]/section[@class=&quot;mt-50 pb-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-8 col-lg-10 m-auto&quot;]/div[@class=&quot;contact-from-area  padding-20-row-col wow tmFadeInUp animated animated&quot;]/form[@class=&quot;contact-form-style text-center contact-form&quot;]/div[@class=&quot;form-group text-left&quot;]/div[@class=&quot;contact-message contact-error-message mt-30&quot;]</value>
      <webElementGuid>51e55014-924e-4f3d-8ed2-285a9460d770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/section/div/section/div/div/div/div/form/div[2]/div[2]</value>
      <webElementGuid>6766a529-60c1-4feb-ae31-eeb65e66c27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]</value>
      <webElementGuid>e4255681-5a4a-4762-9563-0a3b13e11bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email is requiredContent is required' or . = 'Email is requiredContent is required')]</value>
      <webElementGuid>4b03059f-86b4-4647-9f61-c965b33e89a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
