<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Drop Us a Line Contact Us For Any Q_5a6bfd</name>
   <tag></tag>
   <elementGuidId>544f8356-4707-443e-b603-ad592332ff61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.mt-50.pb-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/section/div/section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>3fb9d5bc-d5b1-4ef6-b8b9-ee5ec47df098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-50 pb-50</value>
      <webElementGuid>f89cdaca-0b42-4ce6-b406-938445af5d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drop Us a Line Contact Us For Any Questions        Send message Send message successfully! </value>
      <webElementGuid>f479b8a0-ea07-492b-9553-191689bf2b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;mt-60 mb-60&quot;]/div[@class=&quot;ck-content&quot;]/section[@class=&quot;mt-50 pb-50&quot;]</value>
      <webElementGuid>69157ef5-063c-4f49-ba98-05c66dc44b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/section/div/section</value>
      <webElementGuid>05e69225-9eb2-4dbe-b7d9-301e5ece9554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/section</value>
      <webElementGuid>58c316fc-e869-4235-8750-f0ff7280c287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Drop Us a Line Contact Us For Any Questions        Send message Send message successfully! ' or . = 'Drop Us a Line Contact Us For Any Questions        Send message Send message successfully! ')]</value>
      <webElementGuid>7ac6c582-ba26-4bbf-9441-f31f37dc9cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
