<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sarees_hover-img</name>
   <tag></tag>
   <elementGuidId>8c13c973-bd19-4bef-90db-05016d9f3b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.hover-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@aria-label=&quot;Add To Compare&quot;])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Women Yellow Bandhani Printed Maxi Dress Women Yellow Bandhani Printed Maxi Dress&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>64735663-3d84-43cd-8c72-c5a5065625cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-img</value>
      <webElementGuid>da681c5c-b683-4e29-a56a-2f17c7eeb375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/products/2-110-400x400.jpg</value>
      <webElementGuid>e717df50-83d4-46e4-901b-1de2e14a7463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Women Yellow Bandhani Printed Maxi Dress</value>
      <webElementGuid>307ab3db-d8b6-4323-a7f3-32a3d4587cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;ck-content&quot;]/section[@class=&quot;bg-grey-9 section-padding-60&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;tab-content wow fadeIn animated animated&quot;]/div[@class=&quot;tab-pane fade show active&quot;]/div[@class=&quot;row product-grid-4&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-img-action-wrap&quot;]/div[@class=&quot;product-img product-img-zoom&quot;]/a[1]/img[@class=&quot;hover-img&quot;]</value>
      <webElementGuid>08dde89d-ad62-4b1f-8310-3df8dbed7c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section[4]/div/div[2]/div/div/div/div/div/div/a/img[2]</value>
      <webElementGuid>c33f777e-9575-4c0e-963e-3e2ec6df9416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Women Yellow Bandhani Printed Maxi Dress'])[2]</value>
      <webElementGuid>dfeb680b-0aed-4d02-ab80-5cd75e9a2c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>65f347e3-887e-4d39-887d-ea781762e2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://crazystylezs.com/storage/products/2-110-400x400.jpg' and @alt = 'Women Yellow Bandhani Printed Maxi Dress']</value>
      <webElementGuid>25510049-1f44-40e5-b7f0-51fa550edb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Women Yellow Bandhani Printed Maxi Dress'])[4]</value>
      <webElementGuid>9742182d-c4b0-4dd0-95d7-5e1a7bfa1065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
