<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rs.800.00</name>
   <tag></tag>
   <elementGuidId>789cc0a7-d862-4426-b512-643d5350d057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h5/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82c3caf4-01eb-4c2b-aa59-fc451dde59b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rs.800.00</value>
      <webElementGuid>baec5e69-9cbe-4e27-9a93-cc221307604b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;single-product&quot;]/header[@class=&quot;header-area header-style-1 header-height-2&quot;]/div[@class=&quot;header-middle header-middle-ptb-1 d-none d-lg-block&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header-wrap&quot;]/div[@class=&quot;header-right&quot;]/div[@class=&quot;header-action-right&quot;]/div[@class=&quot;header-action-2&quot;]/div[@class=&quot;header-action-icon-2&quot;]/div[@class=&quot;cart-dropdown-wrap cart-dropdown-hm2 cart-dropdown-panel&quot;]/div[@class=&quot;shopping-cart-footer&quot;]/div[@class=&quot;shopping-cart-total&quot;]/h5[1]/span[1]</value>
      <webElementGuid>bdd127a4-a04a-495a-81b6-32ae7ce34762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/span</value>
      <webElementGuid>2a949a87-016f-4848-8cac-1c82eb58ae06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rs.800.00' or . = 'Rs.800.00')]</value>
      <webElementGuid>49a2d009-4c04-4240-81a5-b090510424ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
