<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Current password  New password  Passwo_de4ee7</name>
   <tag></tag>
   <elementGuidId>b4f9e422-6f62-471f-8c04-0b2330d5318d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-body > form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='https://classicculture.in/customer/change-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d1dd6632-9dd3-4762-ae2f-0b634fd35275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>9e0a15fb-74fb-4c88-bee1-c8f88c89173f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>https://classicculture.in/customer/change-password</value>
      <webElementGuid>29f15a44-6d27-48c7-94e7-bf60e6cbd7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-charset</name>
      <type>Main</type>
      <value>UTF-8</value>
      <webElementGuid>c3c6933f-d599-4f84-9a89-a652f31a5ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Current password:  New password:  Password confirmation:  Change password</value>
      <webElementGuid>aa7b627b-4377-4b7c-846f-a9bba52f5f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[1]</value>
      <webElementGuid>3ecb857e-29a1-430c-9759-563b8658a06e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='https://classicculture.in/customer/change-password']</value>
      <webElementGuid>09e7fac6-531f-4ccd-bec8-de4fe85a8eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/form</value>
      <webElementGuid>ad304376-9656-453b-badb-97837da1761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change password'])[2]/following::form[1]</value>
      <webElementGuid>86fb042e-768c-4825-aef6-5c4e05bb1afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::form[1]</value>
      <webElementGuid>865350d5-d147-4ede-9ddc-2d8c19e17679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form</value>
      <webElementGuid>852d45e3-f8cf-4703-8f2a-55c02f68dad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = ' Current password:  New password:  Password confirmation:  Change password' or . = ' Current password:  New password:  Password confirmation:  Change password')]</value>
      <webElementGuid>f67e548d-6aef-4210-961e-d01ab0de1217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
