<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password confirmation_password_confirmation</name>
   <tag></tag>
   <elementGuidId>5b9fad09-96fb-4c76-b4bc-b87b08cae96d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_confirmation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caf4101f-5ad6-43e3-bdf9-1326fb067094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7f4cf047-c46b-40f3-b26a-674f33469be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1f244d55-08c8-4ca2-a0f0-a986a98cb471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_confirmation</value>
      <webElementGuid>869d2355-4c33-4f5e-9ff5-03ad0da12338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_confirmation</value>
      <webElementGuid>c850e910-1541-49fe-8ba9-bbc9fcd0a153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password confirmation</value>
      <webElementGuid>1665cc79-c4c7-47c8-b8d5-f42ed437de94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control square</value>
      <webElementGuid>e35e1002-e896-40a8-adb2-8765e76e3bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_confirmation&quot;)</value>
      <webElementGuid>1b137d03-3eb8-4486-865c-eabe1062a132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_confirmation']</value>
      <webElementGuid>db2c9573-5fe5-4f60-8b24-9374a054330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/form/div[3]/input</value>
      <webElementGuid>ca957f4c-75e0-4342-adad-3229a3e8c439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>8e50bdb1-4127-436a-87e2-c34610051411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password_confirmation' and @id = 'password_confirmation' and @placeholder = 'Password confirmation']</value>
      <webElementGuid>f8651bf4-63e4-4eb0-be28-2a2ae0b09444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
