<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Upload photos</name>
   <tag></tag>
   <elementGuidId>208bdc5d-c0e1-431d-a012-17f74566a0e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='image-upload__uploader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.image-upload__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e91ed77-53f4-4d97-ad16-dc61c7c47b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-upload__text</value>
      <webElementGuid>09bbd313-9920-4cb4-ab9b-504b759c3510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload photos</value>
      <webElementGuid>2cfd348b-c010-4508-952e-177eb0cd2d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reviews&quot;)/div[@class=&quot;comment-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-md-12&quot;]/form[@class=&quot;form-contact comment_form form-review-product&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;image-upload__viewer d-flex&quot;]/div[@class=&quot;image-viewer__list position-relative&quot;]/div[@class=&quot;image-upload__uploader-container&quot;]/div[@class=&quot;d-table&quot;]/div[@class=&quot;image-upload__uploader&quot;]/div[@class=&quot;image-upload__text&quot;]</value>
      <webElementGuid>714de0de-87fd-431c-9e31-7f69480fe676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Reviews']/div/div[2]/div/form/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>b2f9ff91-7adc-43d0-9f43-9635d274d3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality'])[1]/following::div[9]</value>
      <webElementGuid>2f469320-8e6b-4cf3-82e2-1f839ddc1d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a review'])[1]/following::div[13]</value>
      <webElementGuid>907e4f73-2f98-4363-8f87-ccd355018e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can upload up to 6 photos, each photo maximum size is 2048 kilobytes'])[1]/preceding::div[5]</value>
      <webElementGuid>4eef991f-d15f-4d9f-9be2-8a88f2eb92ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Review'])[1]/preceding::div[6]</value>
      <webElementGuid>752167fb-632f-46dc-896a-29d33b78aa10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload photos']/parent::*</value>
      <webElementGuid>6c0cec1b-4ac9-4f1c-a3ac-88a35e9ad214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>14656d00-7129-45ef-bd7c-c210480b69e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Upload photos' or . = 'Upload photos')]</value>
      <webElementGuid>3cb4a276-7101-4f61-add3-0656440ca780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
