<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscribe</name>
   <tag></tag>
   <elementGuidId>65329b0a-7dee-4b81-aa82-f134fbd8e440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide02']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slick-slide02</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cabd9a6-870d-4f00-9acf-4114b576dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/3.jpg</value>
      <webElementGuid>0726dcd5-d18c-48d8-8eee-b78edf4d1fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablet-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/3.jpg</value>
      <webElementGuid>9c12d8cf-9132-4e51-8d72-1be0fedeac9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-image</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/sliders/3.jpg</value>
      <webElementGuid>232d777a-abba-41b0-b561-ae34d6c9535d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>single-hero-slider single-animation-wrap slick-slide slick-current slick-active</value>
      <webElementGuid>253f69a5-7063-4f2e-81f1-c788a1217d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slick-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>89719c4f-4f3f-4b6a-bb32-25133b86fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3ffb97d-e500-4bc2-89b4-525ddfb828d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ce7391e-c254-4bec-bc0b-f047da099403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>398b694e-7b06-47a5-96d3-daa1a836c7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slick-slide02</value>
      <webElementGuid>7707e970-387d-410c-b6f6-a4de11d48e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>slick-slide-control02</value>
      <webElementGuid>822ef786-dbb2-4b9a-8eea-6535af2c1f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Subscribe</value>
      <webElementGuid>163f1162-9a52-431b-9b36-b61332a6c0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide02&quot;)</value>
      <webElementGuid>8c9d485b-aef9-4b10-8764-1bc786df178f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slick-slide02']</value>
      <webElementGuid>20ff0f7d-a760-4b89-a41f-112ce456e92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>a01f346f-ff28-427f-92fc-80e4e32fbc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[2]/following::div[1]</value>
      <webElementGuid>94813959-05b9-439b-9821-1f3440280a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/following::div[5]</value>
      <webElementGuid>346fecd4-c878-45dc-b216-fc22a2e315dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[4]/preceding::div[4]</value>
      <webElementGuid>88425c9f-3e5f-47aa-adfe-d256aa61ff36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>e99ef962-9757-46a8-b3c7-e5a62793a04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slick-slide02' and (text() = '  Subscribe' or . = '  Subscribe')]</value>
      <webElementGuid>e35d8db9-15af-42a6-b45a-1568cf4c6b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slick-slide01']</value>
      <webElementGuid>3e46b640-1901-4d40-a3bc-1e58da29c49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>e002ef16-1be0-4686-9d83-f68f9e394df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/following::div[1]</value>
      <webElementGuid>137718e9-5029-4bd2-9104-92b273497638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 DEEPTECH SOLUTIONS. All rights reserved'])[1]/following::div[13]</value>
      <webElementGuid>6216639a-7bb1-442f-9ec7-23cec9fba3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[3]/preceding::div[4]</value>
      <webElementGuid>c1939553-db9c-46b3-ab4e-31119719472a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f9864fea-345f-457b-b835-01c15d283c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slick-slide01' and (text() = '  Subscribe' or . = '  Subscribe')]</value>
      <webElementGuid>db7d25ef-cb7a-4619-b33c-651b436ddac2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
