<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Order Return Requests ID number Order I_42f1bd</name>
   <tag></tag>
   <elementGuidId>6886be40-a7fa-4381-b123-997aec635d1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tab-content.account.dashboard-content.pl-50</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>521a91f9-f925-4a14-97df-9854701c5204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-content account dashboard-content pl-50</value>
      <webElementGuid>8231ea51-72af-488e-a940-00da3fe3f51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Return Requests ID number Order ID number Items Count Date Status Actions #10000009 #10000529 2 Oct 13, 2023 04:10 Completed View #10000005 #10000497 2 Oct 12, 2023 08:10 Completed View </value>
      <webElementGuid>0ae55e79-39f7-4962-87bf-ce4ce55b5c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;page-content pt-150 pb-150&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 m-auto&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;tab-content account dashboard-content pl-50&quot;]</value>
      <webElementGuid>ebd69484-2641-4524-b822-b33661e5d998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>a924f413-169b-4cdf-b4a3-24210915db1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[2]</value>
      <webElementGuid>d6a1527a-12eb-4061-9cec-65d7c2fe3517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a vendor'])[1]/following::div[2]</value>
      <webElementGuid>9699a590-b174-4b0a-8075-be359ce1667a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>eca652b1-c794-41b9-a8c5-bdea930979bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Order Return Requests ID number Order ID number Items Count Date Status Actions #10000009 #10000529 2 Oct 13, 2023 04:10 Completed View #10000005 #10000497 2 Oct 12, 2023 08:10 Completed View ' or . = 'Order Return Requests ID number Order ID number Items Count Date Status Actions #10000009 #10000529 2 Oct 13, 2023 04:10 Completed View #10000005 #10000497 2 Oct 12, 2023 08:10 Completed View ')]</value>
      <webElementGuid>7ccd3802-8bcc-4d06-a2bb-98b5835add51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
