<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews (1)</name>
   <tag></tag>
   <elementGuidId>99bc0fe0-2686-457c-8485-04f8aad4470c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reviews-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Reviews-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0503508a-98bc-4a45-a718-779922d0f7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reviews-tab</value>
      <webElementGuid>35da506a-ab34-4075-8699-d9f492699d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b54de43d-4b25-469b-954b-4af128748361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Reviews</value>
      <webElementGuid>b6b55d6c-c800-417a-b639-18a9660cdd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>1968aef0-7d98-456a-8352-6dd12f7527d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reviews (1)</value>
      <webElementGuid>4b3bd481-f31b-4bf2-9c38-1cd8dd25aca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reviews-tab&quot;)</value>
      <webElementGuid>88c9e308-2969-4f2c-8de3-0e642e024dbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Reviews-tab']</value>
      <webElementGuid>c5560b1f-b663-4fd5-8dc7-2cc7c9db7b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>f1ab51d9-91e2-4884-9e4f-22d1db2a19ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reviews (1)')]</value>
      <webElementGuid>02699561-e403-474f-ae07-2057cfbdaaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::a[1]</value>
      <webElementGuid>214173c5-d974-483c-85ec-4bdb12fff624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DETAILS'])[1]/preceding::a[1]</value>
      <webElementGuid>2d533057-89cc-4d9a-83dd-9fdf71dafe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yellow printed woven maxi dress, has a round neck, three-quarter sleeves, and flared hem'])[1]/preceding::a[1]</value>
      <webElementGuid>36abad63-f84d-4c14-be82-de8302f9d876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviews (1)']/parent::*</value>
      <webElementGuid>5aef29a8-8d71-4596-a59a-bb31b21a39a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#Reviews')])[2]</value>
      <webElementGuid>85988d2e-9052-40d2-96b0-a61c8dfdd071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>b2bb2b40-a014-4c89-a9b5-c23aa52de9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'Reviews-tab' and @href = '#Reviews' and (text() = 'Reviews (1)' or . = 'Reviews (1)')]</value>
      <webElementGuid>a5605871-7ce3-4989-836f-4a7a0ab59e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
