<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>356fb4cf-afb6-413d-b2ab-738a401ecee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79466fa4-8db4-4b22-a81a-a347845e1aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>21cbc021-0aa9-4270-a186-95671e56a4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>808874cf-00bb-4006-bc3d-d9b7726b0633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-email</value>
      <webElementGuid>7afd121c-aa36-4663-af34-1c7cf0881ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>93cec321-262a-41cf-b3db-240ceb0b7886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username or Email*</value>
      <webElementGuid>34b6aca6-6b26-4d2d-aee1-bf8e8192a631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-email&quot;)</value>
      <webElementGuid>cf8d8140-f64b-464e-8732-0afb8f488f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-email']</value>
      <webElementGuid>28a5a4e7-fa2f-4426-83f1-07b85afe6eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div/div/div[2]/div/div/form/div/input</value>
      <webElementGuid>54ab5e7c-fd1b-479e-97cb-59d40b872035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f73f1bf7-4d5b-4ccc-823f-a638dbb5b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'txt-email' and @type = 'email' and @placeholder = 'Username or Email*']</value>
      <webElementGuid>6c171917-4841-4204-ad4f-ec5cfcb6a972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
