<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_land Islands_payment-info-loading</name>
   <tag></tag>
   <elementGuidId>2b8b5454-c8f6-4da9-a27a-d24f12ebc925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.iti__selected-flag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05e25727-fb71-4dc7-b367-c52755696d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__selected-flag</value>
      <webElementGuid>6960df29-3424-4c1a-afb0-a37ce39f7289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-checkout-product-info&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-md-6 left&quot;]/div[@class=&quot;form-checkout&quot;]/div[1]/div[@class=&quot;customer-address-payment-form&quot;]/div[@class=&quot;address-form-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;iti iti--allow-dropdown&quot;]/div[@class=&quot;iti__flag-container&quot;]/div[@class=&quot;iti__selected-flag&quot;]</value>
      <webElementGuid>f2d1c849-c533-48f4-bf8c-e4d651705a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>84103d2d-b126-4bd7-9e14-45c3f53fbce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>iti-7__country-listbox</value>
      <webElementGuid>7a202d8a-d6f5-4303-a1c6-cde6041646f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>iti-7__country-listbox</value>
      <webElementGuid>1340df0d-d2da-4f11-a8af-82f8341acb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc6e0e8f-09d3-4732-aa70-6a73a2987fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d5a6ba2-56b0-4ec9-a3cf-8d3dad11217d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>194f3c02-0dd1-49fa-97c9-55c6b603d267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[2]/following::div[12]</value>
      <webElementGuid>c5754f1f-c794-4cf0-96eb-a4198d9193d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/following::div[15]</value>
      <webElementGuid>b0cb76c4-d3cc-44cc-b5e0-73bea0aa8e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::div[5]</value>
      <webElementGuid>fd2da38a-f3ea-4759-9a3c-31d036cf2b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/preceding::div[7]</value>
      <webElementGuid>e1c6643e-32ed-4975-a9b4-ab0aad9b3f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>f593ddf1-5a53-4812-95d0-d0ae34e3d5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>09ce9613-273d-4b25-bf01-b714ece16cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[1]/following::div[12]</value>
      <webElementGuid>f8f13e6a-1866-48e8-a78f-d618a378daad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::div[14]</value>
      <webElementGuid>b8d0ed83-ec44-4fd5-95b2-aab5d866253a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment method'])[1]/preceding::div[2]</value>
      <webElementGuid>30cc8608-5fd1-4bdc-a7e3-4a4bda9e78b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Payment'])[1]/preceding::div[2]</value>
      <webElementGuid>e4bf525b-c1b3-4b4b-8a09-1c6833d7094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>76ec6d68-c6cc-4407-b4d4-53f79fdaca95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
