<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping information_addressname</name>
   <tag></tag>
   <elementGuidId>39c39c30-52c9-4b3f-b42f-5a2057d80baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4adb393-8229-4043-8de9-a78d32efb9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d2adfc9-a025-4af1-b049-d9fff019f741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[name]</value>
      <webElementGuid>3917f551-7902-4dd8-83f7-50b06e7fe803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_name</value>
      <webElementGuid>213ed324-f726-404a-b751-6fcbdcc2240c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>6115472d-028e-4524-8c6a-9c0d94cae60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>7226c1df-1e62-4fd6-a298-548b67546078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_name&quot;)</value>
      <webElementGuid>cedce1c6-bb16-4b69-b5e9-3c99d5aaf6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>john</value>
      <webElementGuid>0993bd22-5d0e-43f9-ac89-ecf8ed425e62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_name']</value>
      <webElementGuid>8e3f4eae-1a1c-463e-8e78-eab02e68d778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>2fa32c4e-42c1-4b73-a699-4448ac57fb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>db4e8737-3a5e-4004-8b0d-3227b2de0e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address[name]' and @id = 'address_name' and @placeholder = 'Full Name']</value>
      <webElementGuid>219ec703-7c29-466b-a4b3-0ae9f38a1d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
