<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_addressaddress</name>
   <tag></tag>
   <elementGuidId>04204158-f258-44f6-aa2f-4551eabd455a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3cd297d-220f-4e46-a6c4-af752fcc8492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_address</value>
      <webElementGuid>69f8961b-0aba-4e60-adbb-efcdf618aef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>271d4490-414d-48da-89b8-1a59ed668aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input</value>
      <webElementGuid>40d21fb0-28c8-4a08-983e-f27e416aa9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>588fda57-334b-4e60-bbf9-388bee392ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[address]</value>
      <webElementGuid>d0af6722-2231-47af-929a-b17329c19824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_address&quot;)</value>
      <webElementGuid>cfd0fe8e-9c44-488a-8157-93b1a7dcd907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>punjab</value>
      <webElementGuid>40a2118d-322d-479c-aa8d-0914a17a687b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_address']</value>
      <webElementGuid>23f8f022-9730-48b2-bb25-4cb4e9fab213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[3]/div[4]/div/input</value>
      <webElementGuid>f8f8314d-092d-4f6e-afc7-947d6e8c5924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ae657d5d-c3da-41ec-a584-7b4d558c4fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_address' and @type = 'text' and @placeholder = 'Address' and @name = 'address[address]']</value>
      <webElementGuid>e45763cd-882b-49e2-9ad7-22095a5704c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
