<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_addressphone</name>
   <tag></tag>
   <elementGuidId>c3586c07-0355-41bb-a504-0b3f400e2042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa6a9575-2f68-4977-a44c-086d1627d1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_phone</value>
      <webElementGuid>065d616b-9911-45f8-9dc9-81add470f52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control address-control-item address-control-item-required checkout-input js-phone-number-mask form-control</value>
      <webElementGuid>59657e0f-989c-4e60-be4f-065dd508f88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[phone]</value>
      <webElementGuid>3333c0c1-3f15-4b03-b412-4613f0bbfb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84415305-bbc8-44d0-82b9-2ebeb030172e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>285572ad-e9a6-48bc-b75f-7432ac07d60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>081234 56789</value>
      <webElementGuid>1797f2ce-a4bb-4e54-ae7f-d086af4bbf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>8f43d602-964f-429e-9a11-060cc9c75c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_phone&quot;)</value>
      <webElementGuid>1b36a4d8-f118-40fc-af57-055a1807e458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8975845258</value>
      <webElementGuid>56b041bf-ad50-4684-a603-07c18f90a115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_phone']</value>
      <webElementGuid>5501f0d5-43fc-4f77-b4b6-d6c32231146e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-checkout-product-info']/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>3e8e78ea-25be-4ac0-a726-98769b5d6520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>ba4e6442-4983-41d5-afa1-8febb1e74bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_phone' and @name = 'address[phone]' and @type = 'text' and @placeholder = '081234 56789']</value>
      <webElementGuid>b3516290-8e22-4598-8157-d1e8faeae456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_phone' and @name = 'address[phone]' and @type = 'text']</value>
      <webElementGuid>af61abfb-fba0-4434-b638-4caf0a1d0ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
