<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Navy Blue Ethnic Motifs Pleated Keyhole _368a01</name>
   <tag></tag>
   <elementGuidId>254efed3-d1a8-44ac-b073-0d83c366da21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[4]/div/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f5891559-ccb4-4525-8d23-c4cec00680b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Navy Blue Ethnic Motifs Pleated Keyhole Neck Top</value>
      <webElementGuid>dc858708-2126-42fe-9075-67cad87aa58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-xxl-3 col-xl-3 col-lg-4 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-content-wrap&quot;]/h2[1]</value>
      <webElementGuid>d866b7a5-0509-41fe-8f89-23c4719cf857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[4]/div/div[2]/h2</value>
      <webElementGuid>7050f352-ce83-4dcc-a5b8-798eca0ad8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops and Tunics'])[5]/following::h2[1]</value>
      <webElementGuid>fa56849c-8bfe-46b9-93f8-13ba48fa8833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::h2[1]</value>
      <webElementGuid>21a2d909-5830-454c-a408-c79d4395318d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[18]/preceding::h2[1]</value>
      <webElementGuid>df0b7f5a-0d2e-4224-aa3a-a0a4624cbba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/h2</value>
      <webElementGuid>29e9be0b-63a3-4656-80d3-bc60ca5524cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Navy Blue Ethnic Motifs Pleated Keyhole Neck Top' or . = 'Navy Blue Ethnic Motifs Pleated Keyhole Neck Top')]</value>
      <webElementGuid>90884357-5a29-48fb-a9fa-05f81bb5ad0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
