<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hot Computer Accessories 620 Retro Game_89ae1b</name>
   <tag></tag>
   <elementGuidId>a229d72f-0dce-429d-acec-64da55223def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c72d2661-fe25-44c3-a823-82288a008791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-cart-wrap mb-30</value>
      <webElementGuid>6c6881cc-50b4-4a99-bfa7-ec9fbf738df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Hot Computer Accessories 620 Retro Game Console,Classic Mini Game System with Preloaded Video Games and 2 Classic Controllers,AV Output Plug&amp;Play Console for Kids and Adults Rs.3,299.00  Add</value>
      <webElementGuid>76e0d0a4-3f7d-4d90-99bd-1ae3407d65ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-xxl-3 col-xl-3 col-lg-4 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]</value>
      <webElementGuid>9d5f572f-369b-43d6-a5bf-29b3eaaee054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[4]/div</value>
      <webElementGuid>8876e85c-90df-45a6-aef7-e2893a395b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[3]/following::div[2]</value>
      <webElementGuid>5e0c2038-90ed-42a1-90cb-5e379eab5a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.2,368.00'])[1]/following::div[3]</value>
      <webElementGuid>bed0b1c4-259c-43d0-852c-127bd1fb2093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div</value>
      <webElementGuid>ac6c9ae5-95eb-4456-8db6-419cbd6b963f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '     Hot Computer Accessories 620 Retro Game Console,Classic Mini Game System with Preloaded Video Games and 2 Classic Controllers,AV Output Plug&amp;Play Console for Kids and Adults Rs.3,299.00  Add' or . = '     Hot Computer Accessories 620 Retro Game Console,Classic Mini Game System with Preloaded Video Games and 2 Classic Controllers,AV Output Plug&amp;Play Console for Kids and Adults Rs.3,299.00  Add')]</value>
      <webElementGuid>69f529d7-f3a1-4590-88da-a09f6a318c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
