<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hot Cameras 4K Digital Camera 48MP Vide_3b7aa4</name>
   <tag></tag>
   <elementGuidId>0bf57701-51ae-45dd-b334-8f92ae16418b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[11]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>171f997b-96b2-4a96-ba72-58e7bb3c1b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-cart-wrap mb-30</value>
      <webElementGuid>23095137-3307-4d21-b02b-663f807f8e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Hot Cameras 4K Digital Camera 48MP Video Camera Camcorder Rs.18,999.00  Add</value>
      <webElementGuid>bc076c5c-9eb6-468e-957c-23d6ce3634ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-xxl-3 col-xl-3 col-lg-4 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]</value>
      <webElementGuid>2e998153-75c0-47ad-a751-662006e375c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[11]/div</value>
      <webElementGuid>77186c5c-6e1b-4ae7-b408-7fa997e67783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[10]/following::div[2]</value>
      <webElementGuid>a80bedfd-9d1f-4d81-980a-9c70d09ef47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.851.00'])[1]/following::div[3]</value>
      <webElementGuid>0fccd62b-89f9-45fa-b2e1-53d50c33812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div</value>
      <webElementGuid>07c8c876-6173-4fc5-b0bf-ea8ed05445bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '     Hot Cameras 4K Digital Camera 48MP Video Camera Camcorder Rs.18,999.00  Add' or . = '     Hot Cameras 4K Digital Camera 48MP Video Camera Camcorder Rs.18,999.00  Add')]</value>
      <webElementGuid>9a79e1d5-33d8-46e6-af20-0a1c39fde159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
