<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add_hover-img</name>
   <tag></tag>
   <elementGuidId>2cc35713-8709-4347-869b-23638bc6f5dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[3]/div/div/div/a/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66bd4e06-966f-4b4f-acdc-4c78dc1d189e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/products/3-179-400x400.jpg</value>
      <webElementGuid>64afd13d-1212-4862-889e-061fc1682106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TikiTunes Portable Bluetooth 5.0 Indoor/Outdoor Wireless Speakers, LED Torch Atmospheric Lighting Effect, 5-Watt Audio USB Speakers, 2000 mAh Battery</value>
      <webElementGuid>53cbffa7-65c9-4282-87b8-c30605ec6c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-img</value>
      <webElementGuid>800dd3ea-73b2-40da-a67b-5d23e4f2e6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-xxl-3 col-xl-3 col-lg-4 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-img-action-wrap&quot;]/div[@class=&quot;product-img product-img-zoom&quot;]/a[1]/img[@class=&quot;hover-img&quot;]</value>
      <webElementGuid>208c0925-88fb-4b4a-a398-e36044a97a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[3]/div/div/div/a/img[2]</value>
      <webElementGuid>469d2be0-78b0-4531-81af-de071a415883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='TikiTunes Portable Bluetooth 5.0 Indoor/Outdoor Wireless Speakers, LED Torch Atmospheric Lighting Effect, 5-Watt Audio USB Speakers, 2000 mAh Battery'])[2]</value>
      <webElementGuid>f31728b6-8ad2-4655-a7ce-9cfabedeffb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img[2]</value>
      <webElementGuid>83dea1c6-e397-49fe-9aa4-fa99bf6a80fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://crazystylezs.com/storage/products/3-179-400x400.jpg' and @alt = 'TikiTunes Portable Bluetooth 5.0 Indoor/Outdoor Wireless Speakers, LED Torch Atmospheric Lighting Effect, 5-Watt Audio USB Speakers, 2000 mAh Battery']</value>
      <webElementGuid>c38c9729-2f10-4353-9afe-3de42d782465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
