<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Faq</name>
   <tag></tag>
   <elementGuidId>8e8e7e37-b636-4cc5-b8c9-233155a40113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.breadcrumb-item.d-inline-block.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04820261-b502-4e45-8d1d-40057e26fe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>itemListElement</value>
      <webElementGuid>51095e62-69ce-4ad2-ba1f-1a2d89e23e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemscope</name>
      <type>Main</type>
      <value>itemscope</value>
      <webElementGuid>a728b410-cdad-418a-8f97-6f703c64edfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemtype</name>
      <type>Main</type>
      <value>http://schema.org/ListItem</value>
      <webElementGuid>d2aaf051-b559-4797-897f-c91349de5d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-item d-inline-block active</value>
      <webElementGuid>1ccaef28-79ce-481b-bf99-207599fecb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Faq
                              </value>
      <webElementGuid>2eaee303-f970-4c2e-87a8-5abb539dd532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;page-header breadcrumb-wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;breadcrumb&quot;]/div[@class=&quot;breadcrumb-item d-inline-block active&quot;]</value>
      <webElementGuid>27f5e11e-46ef-49ea-a59e-6fc780ab3331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/div/div/div[2]</value>
      <webElementGuid>dd7fea2d-01db-4666-a113-b70a0d772ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[2]</value>
      <webElementGuid>6e1ac7e3-db02-43da-806d-017ef13cc2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                Faq
                              ' or . = '
                                Faq
                              ')]</value>
      <webElementGuid>a0756f82-d557-4780-8d62-f49df7201120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
