<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_btn-close_1</name>
   <tag></tag>
   <elementGuidId>ae809ff5-488f-479d-adf5-bae3b248e191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef12859c-9bf3-437e-8878-ea6d493cd186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close</value>
      <webElementGuid>c7dc1ed0-bca3-4977-a9d5-23f578964c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>51125f1d-c1f3-4962-935f-a33f19a7c184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>38ef548a-155f-4bf5-922b-0097c601f594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;767&quot;]/span[@class=&quot;btn-close&quot;]</value>
      <webElementGuid>752ae1ec-3281-4a93-b550-fb70df1113b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
