<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Subscribe  Subscribe  Subscribe  Su_4dbd16</name>
   <tag></tag>
   <elementGuidId>b6dc4223-5abb-4235-a57c-d260d05b5fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.home-slider.style-2.position-relative.mb-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div/section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>374f03fd-b942-4146-982a-32c0398a23b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-slider style-2 position-relative mb-50</value>
      <webElementGuid>a22a3053-3c90-4b3b-97ee-a736a05c332e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Subscribe  Subscribe  Subscribe  Subscribe   1234   </value>
      <webElementGuid>61f0f939-f6ac-456e-90be-d637aecad29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;ck-content&quot;]/section[@class=&quot;home-slider style-2 position-relative mb-50&quot;]</value>
      <webElementGuid>dfd493c6-880a-4ff1-9ed4-d7972957d09e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div/section</value>
      <webElementGuid>a6fa5f09-aa74-4e22-a7b0-d8c29ce06b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 DEEPTECH SOLUTIONS. All rights reserved'])[1]/following::section[1]</value>
      <webElementGuid>a78157b1-ccf2-4a79-83a6-1ee77e2ad256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Us'])[1]/following::section[1]</value>
      <webElementGuid>ebd3cbba-7f02-4375-882a-48faf6c79b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>1b26134c-f8f8-4331-94d7-6cfab5de9f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = '  Subscribe  Subscribe  Subscribe  Subscribe   1234   ' or . = '  Subscribe  Subscribe  Subscribe  Subscribe   1234   ')]</value>
      <webElementGuid>7075d715-4ddd-41e0-8722-8e37116a4f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
