<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip code_zip_code</name>
   <tag></tag>
   <elementGuidId>8bd85d2c-10f8-4554-87d1-4ef8920770a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zip_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zip_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5e1ab71-954d-4467-ac1c-feb7e357fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zip_code</value>
      <webElementGuid>7f184e3d-7edd-4664-b33f-59f36f555bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c736e95-0634-42cd-b011-62ed2c3a94d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zip_code</value>
      <webElementGuid>75ed7583-fcf1-488a-ae37-738625702038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3c905749-fc00-47b8-add6-595f39681920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your zip code</value>
      <webElementGuid>5707aaa7-7114-4213-a4a8-322ae9c3424d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2e3f3c16-afe3-40cf-bdc0-ab9fb3c19f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zip_code&quot;)</value>
      <webElementGuid>b0daf9f5-fa6c-4a7e-85f4-be9600251e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zip_code']</value>
      <webElementGuid>4d2705b2-a41d-4e53-ba26-16d20cb21098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/div/div[2]/form/div[8]/input</value>
      <webElementGuid>4fe147f9-b947-44a4-b410-94f0346df93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>684a2528-75b1-42d9-bacc-6e2a573d06e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zip_code' and @type = 'text' and @name = 'zip_code' and @placeholder = 'Enter your zip code']</value>
      <webElementGuid>d9751f71-a647-49da-855b-765f8657f9e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
