<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__mfp-img</name>
   <tag></tag>
   <elementGuidId>4f19df7a-a4e1-445e-9765-18683316922d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mfp-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Testing Product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a20ee02-108b-46ea-80c0-18da037ee1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mfp-img</value>
      <webElementGuid>d5300a4d-f707-472a-a0b2-553b72a18275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Testing Product</value>
      <webElementGuid>911a91ae-b64b-47ce-b735-132bec007fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://crazystylezs.com/storage/dropbox-8254221001031053.webp</value>
      <webElementGuid>57791998-c942-49bb-8aea-2c938b3fccff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;single-product mfp-zoom-out-cur&quot;]/div[@class=&quot;mfp-wrap mfp-gallery mfp-close-btn-in mfp-auto-cursor mfp-ready&quot;]/div[@class=&quot;mfp-container mfp-image-holder mfp-s-ready&quot;]/div[@class=&quot;mfp-content&quot;]/div[@class=&quot;mfp-figure&quot;]/figure[1]/img[@class=&quot;mfp-img&quot;]</value>
      <webElementGuid>0f08a116-f2af-475d-be74-0d322fbd37e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Testing Product']</value>
      <webElementGuid>ae39f046-873e-4c49-94bd-f3f564fcf82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>399b42d8-ae47-4fc2-88b6-a9c5d669a6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Testing Product' and @src = 'https://crazystylezs.com/storage/dropbox-8254221001031053.webp']</value>
      <webElementGuid>de7131b7-8fc1-40d5-b918-9ac2da0799a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
