<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ascrollUp</name>
   <tag></tag>
   <elementGuidId>ac197e53-64c3-4c40-b857-04af752aab19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='scrollUp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7cdc320-221e-4a86-8673-c4dc6540bd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scrollUp</value>
      <webElementGuid>d8a9b8f7-03d8-465d-b47c-fd1155a531a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#top</value>
      <webElementGuid>9814e2c3-c53c-4297-91ee-c2eda7ce9e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollUp&quot;)</value>
      <webElementGuid>4aebc041-6eb8-4a8b-aa20-d54006d4c7d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='scrollUp']</value>
      <webElementGuid>b16aee21-f9cc-41bf-80b2-72b9d20346a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#top')]</value>
      <webElementGuid>bb1ad0e7-474b-4247-a02c-f7dd5fec1d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/a</value>
      <webElementGuid>515da55d-cd0c-43ad-bd46-d9d6ea9ffa52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'scrollUp' and @href = '#top']</value>
      <webElementGuid>aad3d28d-f87e-4239-aca4-941fadc437ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
