<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fi-rs-arrow-small-up</name>
   <tag></tag>
   <elementGuidId>988cdcd6-5bbf-4559-8fb9-a02f270fd164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fi-rs-arrow-small-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='scrollUp']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d9ce7166-bb45-44a4-b274-5f18c83d623a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rs-arrow-small-up</value>
      <webElementGuid>f684a7aa-f2db-4e6d-9950-49080fe696b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollUp&quot;)/i[@class=&quot;fi-rs-arrow-small-up&quot;]</value>
      <webElementGuid>139336c5-b3b7-4ee5-a7ba-ab4ca630261a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='scrollUp']/i</value>
      <webElementGuid>2a56b471-dcde-4d61-824d-da4810cc6ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/a/i</value>
      <webElementGuid>33c814fd-5b86-4a93-83b8-10b89170fe41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
