<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Navy Blue Ethnic Motifs Pleated Keyhole Neck Top</name>
   <tag></tag>
   <elementGuidId>cc69f873-3f52-456d-bde4-e8f09122ebf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[4]/div/div[2]/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>abf149e0-2630-40a3-97c5-0dbd04f71aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://crazystylezs.com/products/navy-blue-ethnic-motifs-pleated-keyhole-neck-top-1</value>
      <webElementGuid>26e3d03a-9826-4dd8-b34d-fd0ae0d855c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Navy Blue Ethnic Motifs Pleated Keyhole Neck Top</value>
      <webElementGuid>c32ba4d7-3406-4c16-b9ed-90a29eede7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-xxl-3 col-xl-3 col-lg-4 col-md-4 col-12 col-sm-6&quot;]/div[@class=&quot;product-cart-wrap mb-30&quot;]/div[@class=&quot;product-content-wrap&quot;]/h2[1]/a[1]</value>
      <webElementGuid>307f717c-440e-44d2-8a16-b66ac3b0d2df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[3]/div[4]/div/div[2]/h2/a</value>
      <webElementGuid>e60e2377-6762-4a9d-9355-a7c8bb3db3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Navy Blue Ethnic Motifs Pleated Keyhole Neck Top')]</value>
      <webElementGuid>db84960b-1b19-4f16-adb4-32f77b846c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops and Tunics'])[5]/following::a[1]</value>
      <webElementGuid>c2d3a04c-6791-4356-b579-7307074367d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::a[2]</value>
      <webElementGuid>8e35dc8e-8360-4baa-a758-619342739d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.499.00'])[1]/preceding::a[1]</value>
      <webElementGuid>a4764f46-fe8b-4615-ac8c-16aeda35d023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs.999.00'])[1]/preceding::a[1]</value>
      <webElementGuid>e564e88e-b747-4617-9b2f-afde6f5e5045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Navy Blue Ethnic Motifs Pleated Keyhole Neck Top']/parent::*</value>
      <webElementGuid>bb486d5f-7592-4971-af6c-31bc1eb782cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://crazystylezs.com/products/navy-blue-ethnic-motifs-pleated-keyhole-neck-top-1')])[2]</value>
      <webElementGuid>224a4134-82c0-4402-b006-13f7cbdbc92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/h2/a</value>
      <webElementGuid>9797837a-5064-4a5b-bed3-e8719e65268b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://crazystylezs.com/products/navy-blue-ethnic-motifs-pleated-keyhole-neck-top-1' and (text() = 'Navy Blue Ethnic Motifs Pleated Keyhole Neck Top' or . = 'Navy Blue Ethnic Motifs Pleated Keyhole Neck Top')]</value>
      <webElementGuid>31bb5e74-d109-42ef-8e7f-bf33e8958335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
