<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Default</name>
   <tag></tag>
   <elementGuidId>8c52aef5-622d-4281-8dfa-93bee50f3c16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sort-by-dropdown.products_ajaxsortby.show > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>747641c9-ada0-492e-93cd-bdfcad4c6644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Default</value>
      <webElementGuid>88f6c3aa-4c7d-4b24-b44d-af9bebcac95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://classicculture.in/products?sort-by=default_sorting</value>
      <webElementGuid>f72fd3e9-9e91-48da-a855-68548c1c11e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default</value>
      <webElementGuid>ada79730-7e44-424e-8c63-0f00efcab754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container mb-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 m-auto&quot;]/div[@class=&quot;products-listing position-relative&quot;]/div[@class=&quot;shop-product-filter&quot;]/div[@class=&quot;sort-by-product-area show&quot;]/div[@class=&quot;sort-by-cover products_sortby&quot;]/div[@class=&quot;sort-by-dropdown products_ajaxsortby show&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>f78901ae-9581-4c99-929e-3d4cbe936fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/ul/li/a</value>
      <webElementGuid>4b0e4f91-e60a-4d34-880a-2e2bbd66fa91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Default')]</value>
      <webElementGuid>72688f7e-efa6-404e-b84b-e016a5c4433d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::a[1]</value>
      <webElementGuid>3858ee11-f137-41ba-93c0-2ee3e348c585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show:'])[1]/following::a[4]</value>
      <webElementGuid>adac563d-c862-4e87-85a0-591de0c6a6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oldest'])[1]/preceding::a[1]</value>
      <webElementGuid>ffc496f6-cb5e-4945-91f3-ea2d372bdc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest'])[1]/preceding::a[2]</value>
      <webElementGuid>02449bf0-9a84-4585-9ece-71e938751b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Default']/parent::*</value>
      <webElementGuid>2afa32d0-6d16-45f8-bd26-38fe64dd9989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://classicculture.in/products?sort-by=default_sorting')]</value>
      <webElementGuid>e1b01a9e-02f5-4ff5-9313-4b87dc2267e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li/a</value>
      <webElementGuid>3303c305-c403-4d47-abbb-2a82b375cf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://classicculture.in/products?sort-by=default_sorting' and (text() = 'Default' or . = 'Default')]</value>
      <webElementGuid>70097f28-e20d-47d1-8878-771002123091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
