<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New image_avatar_file</name>
   <tag></tag>
   <elementGuidId>689b0657-fd4b-45a7-b45f-3c68c1ebf417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avatarInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@for='avatarInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27b7e3eb-f7fa-410a-a271-29c440d77a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avatarInput</value>
      <webElementGuid>2aa679c3-ad39-4215-86a3-c870e6a3df78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>avatar_file</value>
      <webElementGuid>10c3058b-2bc7-4b55-aa2f-20a9931ee130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>883b2875-2abc-4c7a-9397-631297eee1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-input avatar-input bg-transparent ms-0</value>
      <webElementGuid>1a599427-253b-4412-847c-eaa9ba2b99e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avatarInput&quot;)</value>
      <webElementGuid>4c581117-10f9-45d7-9671-01ff90681f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='avatarInput']</value>
      <webElementGuid>b47debc5-ed66-4b6c-9809-1d011f2707e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatar-modal']/div/div/form/div[2]/div/div/input[4]</value>
      <webElementGuid>1269b46a-53a8-4a14-b2b2-ddd7f6a1709b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>6fff5b8b-6a39-452a-a8b5-1711fa33697f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'avatarInput' and @name = 'avatar_file' and @type = 'file']</value>
      <webElementGuid>69467835-99ff-43b1-acb8-96f2b90b54a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
