<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Rs.799.00_fi-rs-cross-small</name>
   <tag></tag>
   <elementGuidId>00e88647-fc3f-46ef-bc7d-1dae20b09bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fi-rs-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr/td[6]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>03017dd3-3014-42c5-8b30-8ddc895db96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rs-trash</value>
      <webElementGuid>da6807cd-6002-4b91-bbdb-a4945869424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-section&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mb-80 mt-50 section--shopping-cart&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;table-responsive shopping-summery&quot;]/table[@class=&quot;table table-wishlist table--cart&quot;]/tbody[1]/tr[@class=&quot;pt-30&quot;]/td[@class=&quot;action text-center&quot;]/a[@class=&quot;text-body remove-cart-button&quot;]/i[@class=&quot;fi-rs-trash&quot;]</value>
      <webElementGuid>d31ae875-c4b8-434a-8b4e-33733604828f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-section']/div[2]/div/form/div/div/div/table/tbody/tr/td[6]/a/i</value>
      <webElementGuid>8ecf1362-b8a5-4089-b3ee-314b8bf7cdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>7f4e115b-53e0-4d3b-bf45-57125e93c075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[3]/a/i</value>
      <webElementGuid>74c76db2-7186-486b-9dda-bb1bf425cb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[3]/a/i</value>
      <webElementGuid>5241279d-b7a5-48c3-9db8-a1b7ba878138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[3]/a/i</value>
      <webElementGuid>bc43b28f-06a7-4cd2-a288-dfbf480b4fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>4fe533d5-7ee8-4e96-b725-33d421b3a55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
